#!/usr/bin/env python3
"""
generate_architecture.py — LitScan architecture diagram generator.

Generates docs/assets/architecture.svg (dark theme, 1200x780), showing:
  clients (CLI / Web / API+SSE) -> FastAPI server -> Scanner
  -> Fetcher -> 7 source adapters -> outputs (CSV / log / history / raw).

Usage:
    python docs/scripts/generate_architecture.py

Output: docs/assets/architecture.svg
Dependencies: stdlib only.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "architecture.svg"

SOURCES = ["arXiv", "Semantic Scholar", "Crossref", "OpenReview", "OpenAIRE", "DOAJ", "Europe PMC"]


def box(x, y, w, h, title, sub, fill, stroke, title_fill="#f0f4ff", rx=10):
    sub_lines = sub.split("|")
    tspans = "".join(
        f'<tspan x="{x + w / 2:.0f}" dy="{18 if i else 0}">{s}</tspan>'
        for i, s in enumerate(sub_lines)
    )
    ty = y + (h / 2 - (len(sub_lines) - 1) * 9 + 4)
    return f"""
  <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="1.2"/>
  <text x="{x + w / 2:.0f}" y="{ty:.0f}" text-anchor="middle" font-size="15" font-weight="700" fill="{title_fill}">{title}</text>
  <text x="{x + w / 2:.0f}" y="{ty + 18:.0f}" text-anchor="middle" font-size="11" fill="#8b9cc0">{tspans}</text>"""


def arrow(x1, y1, x2, y2, color="#5b9dff", dashed=False):
    dash = ' stroke-dasharray="5,4"' if dashed else ""
    return (f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" '
            f'stroke-width="1.6" marker-end="url(#ah)"{dash}/>')


# adapter grid: 2 rows
def adapters():
    parts = []
    w, h, gap = 172, 46, 22
    x0 = (1200 - 4 * w - 3 * gap) / 2
    for i, name in enumerate(SOURCES):
        row, col = divmod(i, 4)
        x = x0 + col * (w + gap)
        y = 470 + row * (h + 18)
        enabled = name != "Europe PMC"
        stroke = "#2a3a5f"
        tag = ""
        if not enabled:
            tag = ' <tspan fill="#e8b34b" font-size="9"> (opt)</tspan>'
        parts.append(
            f'<g><rect x="{x:.0f}" y="{y}" width="{w}" height="{h}" rx="8" fill="#141d36" stroke="{stroke}"/>'
            f'<text x="{x + w / 2:.0f}" y="{y + h / 2 + 4:.0f}" text-anchor="middle" '
            f'font-size="12" fill="#c6d4f0">{name}{tag}</text></g>'
        )
    return "\n".join(parts), x0, 470 + 46 + 18


adp_svg, adp_x0, row2_y = adapters()

SVG = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 780" font-family="'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0b1020"/>
      <stop offset="1" stop-color="#121a31"/>
    </linearGradient>
    <marker id="ah" markerWidth="9" markerHeight="7" refX="8" refY="3.5" orient="auto">
      <polygon points="0 0, 9 3.5, 0 7" fill="#5b9dff"/>
    </marker>
  </defs>

  <rect width="1200" height="780" fill="url(#bg)"/>
  <text x="600" y="42" text-anchor="middle" font-size="21" font-weight="800" fill="#f0f4ff">LitScan Architecture</text>
  <text x="600" y="64" text-anchor="middle" font-size="12" fill="#8b9cc0">config.yaml driven · retry &amp; rate-limit aware · proxy supported</text>

  <!-- Layer 1: clients -->
  {box(105, 92, 300, 66, "CLI", "litscan.py · search / history / retry", "#141d36", "#2a3a5f")}
  {box(450, 92, 300, 66, "Web UI", "Jinja2 · / /history /sources /logs", "#141d36", "#2a3a5f")}
  {box(795, 92, 300, 66, "REST API + SSE", "16 endpoints · streaming progress", "#141d36", "#2a3a5f")}

  {arrow(255, 158, 480, 206)}
  {arrow(600, 158, 600, 206)}
  {arrow(945, 158, 720, 206)}

  <!-- Layer 2: server -->
  {box(330, 206, 540, 70, "FastAPI Server", "server/main.py · routes &amp; templates · Pydantic models", "#182647", "#34508c")}

  {arrow(600, 276, 600, 316)}

  <!-- Layer 3: core -->
  {box(105, 316, 300, 74, "Scanner", "core/scanner.py · orchestration", "#182647", "#34508c")}
  {box(450, 316, 300, 74, "Fetcher", "core/fetcher.py · retry x4 · proxy · timeout=45s", "#182647", "#34508c")}
  {box(795, 316, 300, 74, "History / OperationLogger", "core/history.py · core/logger.py", "#182647", "#34508c")}

  {arrow(255, 390, 500, 434)}
  {arrow(600, 390, 600, 434)}
  {arrow(945, 390, 700, 434)}

  <!-- Layer 4: adapters -->
  <text x="{adp_x0:.0f}" y="458" font-size="12" font-weight="700" fill="#8b9cc0">ADAPTERS · core/adapters.py (7)</text>
  {adp_svg}

  <!-- outputs row -->
  {arrow(600, 580, 600, 668, dashed=True)}
  {box(105, 668, 220, 58, "articles.csv", "统一格式结果", "#12182b", "#24406e")}
  {box(355, 668, 220, 58, "log.md", "检索日志", "#12182b", "#24406e")}
  {box(605, 668, 220, 58, "history.json", "搜索历史 (max 200)", "#12182b", "#24406e")}
  {box(855, 668, 220, 58, "out/raw/", "各库原始响应", "#12182b", "#24406e")}

  <text x="1178" y="766" text-anchor="end" font-size="10" fill="#5a6a8f">generated by docs/scripts/generate_architecture.py</text>
</svg>
"""

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(SVG, encoding="utf-8")
print(f"written: {OUT}")
